spring:
  application:
    name: soccer-hub-notifier
  mail:
    host: smtp.gmail.com
    port: 587
    username: ganzii0324@gmail.com
    password: gohqilifysmyvfej
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: qwer1234
    listener:
      simple:
        acknowledge-mode: MANUAL
        default-requeue-rejected: false
